/* ./Euresys_Coaxlink_TLDataStream_9_5_2 */ 

(function == COAXLINK_Stream_StartScan) | 
(function == COAXLINK_Stream_StopScan) | 
(function == COAXLINK_Stream_StreamReset) | 
(function == COAXLINK_Stream_ErrorCountReset) | 
(function == COAXLINK_Stream_StatisticsStartSampling) | 
(function == COAXLINK_Stream_EventCountReset) | 
(function == COAXLINK_Stream_EventNotificationAll) | 
(function == COAXLINK_Stream_EventCountResetAll) | 
