/* ./Euresys_Coaxlink_TLInterface_9_5_2 */ 

(function == COAXLINK_Interface_DeviceUpdateList) | 
(function == COAXLINK_Interface_CxpPoCxpAuto) | 
(function == COAXLINK_Interface_CxpPoCxpTurnOff) | 
(function == COAXLINK_Interface_CxpPoCxpTripReset) | 
(function == COAXLINK_Interface_tInjectError) | 
(function == COAXLINK_Interface_ClearUserActions) | 
(function == COAXLINK_Interface_ExecuteUserActions) | 
(function == COAXLINK_Interface_DiscardScheduledUserActions) | 
(function == COAXLINK_Interface_lPositionReset) | 
(function == COAXLINK_Interface_EventCountReset) | 
(function == COAXLINK_Interface_EventNotificationAll) | 
(function == COAXLINK_Interface_EventCountResetAll) | 
