/* ./Euresys_Coaxlink_TLSystem_6_2_4 */ 

#define COAXLINK_System_TLVendorNameString "System_TLVendorName" 
#define COAXLINK_System_TLModelNameString "System_TLModelName" 
#define COAXLINK_System_TLIDString "System_TLID" 
#define COAXLINK_System_TLVersionString "System_TLVersion" 
#define COAXLINK_System_TLPathString "System_TLPath" 
#define COAXLINK_System_TLTypeString "System_TLType" 
#define COAXLINK_System_GenTLVersionMajorString "System_GenTLVersionMajor" 
#define COAXLINK_System_GenTLVersionMinorString "System_GenTLVersionMinor" 
#define COAXLINK_System_InterfaceUpdateListString "System_InterfaceUpdateList" 
#define COAXLINK_System_InterfaceSelectorString "System_InterfaceSelector" 
#define COAXLINK_System_InterfaceIDString "System_InterfaceID" 
